blank_issues_enabled: false
contact_links:
  - name: AniTrend Community Support
    url: https://github.com/orgs/AniTrend/discussions
    about: Please ask and answer questions here.
  - name: Frequestnly Ased Questions
    url: https://docs.anitrend.co/project/
    about: Please review the FAQ for commonly asked questions.